apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    service: shipping
spec:
  replicas: 2
  selector:
    matchLabels:
      service: shipping
  template:
    metadata:
      labels:
        service: shipping
    spec:
      initContainers:
      - name: wait-for-mysql
        image: mysql:5.7
        command:
          - sh
          - -c
          - |
            until mysql -h mysql -e "SELECT 1 FROM information_schema.tables WHERE table_schema = 'cities' AND table_name = 'cities' LIMIT 1;" ; do
              echo 'waiting for cities.cities table';
              sleep 2;
            done
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: shipping
        image: {{ .Values.image.repo }}/rs-shipping:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # Configure memory allocation in case of heap space failures
        command:
        - "java"
        - "-XX:InitialRAMPercentage=33"
        - "-XX:MaxRAMPercentage=75"
        - "-jar"
        - "shipping.jar"
        ports:
        - containerPort: 8080
        # it's Java it needs lots of memory
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 1024Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
      restartPolicy: Always
      {{- with .Values.shipping.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shipping.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shipping.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.secret }}
      {{- if .Values.secret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.secret.name }}
      {{- end }}
      {{- end }}
